title: "Documentación Académica - Andrea Carrillo"
description: "Documentación de estudios en Ingeniería en Sistemas: conceptos, tecnologías y proyectos académicos en desarrollo de software y análisis de datos."
author:
  name: "Andrea Carrillo"
  github: "AndCarrillo"
url: "https://andcarrillo.github.io"
baseurl: "/skills-github-pages"

# Configuración académica
show_excerpts: true
paginate: 10

# Jekyll settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navegación académica
nav_links:
  - title: "Inicio"
    url: "/"
  - title: "Documentación"
    url: "/posts/"
  - title: "Perfil Académico"
    url: "/about/"

# Configuración de posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Andrea Carrillo"
