title: "Andrea Carrillo - Dev Journey"
description: "Full Stack Developer e Ingeniera en Sistemas compartiendo experiencias reales en desarrollo web, análisis de datos, y tecnologías como C#, Python, SQL y Power BI."
author:
  name: "Andrea Carrillo"
  github: "AndCarrillo"
email: acarrillo.vlk@gmail.com
url: "https://andcarrillo.github.io"
baseurl: "/skills-github-pages"

# Configuración del blog
show_excerpts: true
paginate: 5

# Jekyll settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navegación
nav_links:
  - title: "Inicio"
    url: "/"
  - title: "Posts"
    url: "/posts/"
  - title: "Acerca de"
    url: "/about/"

# SEO y social
twitter:
  username: "AndCarrillo"
social:
  name: "Andrea Carrillo"
  links:
    - "https://github.com/AndCarrillo"

# Configuración de posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Andrea"
